# Generated by Django 5.1.6 on 2025-03-14 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Apenas avaliações maiores que 0 e menores ou iguais a 5.'), django.core.validators.MaxValueValidator(0, 'Apenas avaliações maiores que 0 e menores ou iguais a 5.')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_movie', to='movies.movie')),
            ],
        ),
    ]
